CREATE TABLE ORGANIZACION(
    CV_ORGANIZACION VARCHAR2(8),
    NOMBRE_ORG VARCHAR(100),
    CONSTRAINT CV_ORGANIZACION_PK PRIMARY KEY(CV_ORGANIZACION)
);

CREATE TABLE DO_CLIENTES(
  CV_CLIENTE VARCHAR2(8),
  NOMBRE_CLIENTE VARCHAR2(100) NOT NULL,
  TIPO_CLI VARCHAR2(3),
  CALLE VARCHAR2(50),
  NUMERO VARCHAR2(6),
  COLONIA VARCHAR2(50),
  ESTADO VARCHAR2(30),
  COP VARCHAR2(5),
  NOMBRE_CONTACTO VARCHAR2(50),
  TELEFONO VARCHAR2(15),
  CORREO_ELECT VARCHAR2(40),
  PASSWORD VARCHAR2(24),
  CV_ORGANIZACION VARCHAR2(8),
  CONSTRAINT FK_CV_ORGANIZACION FOREIGN KEY (CV_ORGANIZACION) REFERENCES ORGANIZACION (CV_ORGANIZACION),
  CONSTRAINT CV_CLIENTE_PK PRIMARY KEY(CV_CLIENTE)
 );
 
 CREATE TABLE POES(
  CV_CLIENTE VARCHAR2(8),
  CV_POE NUMBER(4),
  NOMBRE_POE VARCHAR2(60) NOT NULL,
  AP_PATERNO VARCHAR2(60) NOT NULL,
  AP_MATERNO VARCHAR2(60) NOT NULL,
  RFC VARCHAR2(10),
  TARJETA_1 NUMERIC(7) UNIQUE,
  TARJETA_2 NUMERIC(7) UNIQUE,
  CONSTRAINT POES_FK_CV_CLIENTE FOREIGN KEY (CV_CLIENTE) REFERENCES DO_CLIENTES (CV_CLIENTE),
  CONSTRAINT POES_PK PRIMARY KEY(CV_CLIENTE,CV_POE)
 );